bug fixes

diff --git a/makeppk b/makeppk
--- a/makeppk
+++ b/makeppk
@@ -10,6 +10,7 @@
 # Checking if user name is given and setting a group
 new_student=$1
 user_grp=$2
+home_dir="/home/"$new_student  #home dir will be assigned if there is none
 
 if [ -z $new_student ]; then printf "Usage: $0 [x12345678] [group] \nx12345678 - user login \ngroup - user group\nExit...\n"; exit 9; fi
 if [ -z $user_grp ]
@@ -38,10 +39,6 @@ if [ -z $user_grp ]
 fi
 
 # we have user name and group declared.
-
-
-student_dir="/home/"$new_student"/.ssh"
-
 #
 # if new user exists, the group exists too
 # if user is new, then it needs to check the group's existance 
@@ -59,18 +56,19 @@ else echo "user " $new_student " exists"
 	user_grp=$(id -gn $new_student)
 fi
 
-# if user exists does he have home directory? if no lets create
-# setting up a home directory for a user
-student_dir="/home/"$new_student
+student_dir=$(eval echo ~$new_student)
 if [ ! -d $student_dir ]; then
-	mkdir $student_dir
-	chown -R $new_student:$user_grp $student_dir
+    $student_dir=$home_dir
+    mkdir $student_dir
+    chown -R $new_student:$user_grp $student_dir
 fi
 
+student_dir=$student_dir"/.ssh"        # setting up a home directory for a user
+
+#
 # checking if user has a directory /.ssh in his home dir
 # in no, create one and set the ownership of the directory
 #
-student_dir=$student_dir"/.ssh"
 if [ ! -d $student_dir ]; then
 	mkdir $student_dir
 	chown -R $new_student:$user_grp $student_dir
@@ -82,7 +80,12 @@ putty_user=$new_student"@"$host_name           # will make "x00158589@hostname" 
 ########## GENERATING PPK FILE ###################################################
 echo "wait, working..."                        # generates the code - need to wait
 
-puttygen -t rsa -b 2048 -C $putty_user -o $student_login.ppk
+puttygen -t rsa -b 2048 -C $putty_user -o $new_student.ppk
+
+if [[ ! -e $new_student.ppk ]]; then echo "Error: file" $new_student".ppk has not been created. Exit..."; exit 9
+else echo $new_student".ppk file created"
+echo "student_dir="$student_dir
+fi
 
 # extract a public key and copy to student_dir/.ssh/authorized_keys
 puttygen -L $new_student.ppk >> $student_dir"/authorized_keys"  
